### ISSUE TITLE
InspecthiShowInspector does not work with neovim

### ISSUE THREAD

**Issue by ApolloBian** [cocopon/inspecthi.vim#5]
It appears `InspecthiShowInspector` uses `popup_create` which is implemented in vim but not nvim. In nvim we should use floating windows to achieve the same functionality.

**Comment by ApolloBian** [comment]
I have created a PR (#6) to fix this. Comments and suggestions are welcome :-)

There is another PR(#2) that implements same functionality, however I kinda think that implementation is too complex and unnecessary, so I created a new one. I'm ok with either being merged tho.

**Comment by cocopon** [comment]
Merged #6, thank you for your contribution.
